/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.examenmarcosherrero;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class FormularioCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCliente
     */
    public FormularioCliente() {
        initComponents();

    }
    
    private Vector<Cliente> listaClientes =  new Vector<Cliente>();
    private Vector<Movimiento> listaMovimientos = new Vector<Movimiento>();
    
    
    public void leerFormulario() {
        try(BufferedReader bf = new BufferedReader(new FileReader(new File("movimientos.txt")))){
            String linea;
            while((linea = bf.readLine()) != null) {
                String[] lineamovimiento;
                lineamovimiento = linea.split("&&");
                Movimiento mov = new Movimiento(lineamovimiento[0], Double.parseDouble(lineamovimiento[1]));
                this.listaMovimientos.add(mov);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormularioCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormularioCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comprobarClientes() {
        try(PrintWriter pw = new PrintWriter(new FileWriter(new File("ClientesMax.txt")))) {
            for(Cliente c: this.listaClientes) {
                if(c.getTotalventas() >= 3000) {
                pw.println(c.toString());
            }
        }
        } catch (IOException ex) {
            Logger.getLogger(FormularioCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comprobarFicheros() {
        try(PrintWriter pw = new PrintWriter(new FileWriter(new File("Errores.txt")))) {
            for(Movimiento m : this.listaMovimientos) {
                int caca = 0;
            for(Cliente c : this.listaClientes) {
                if(m.getCodigo().equals(c.getCodigo())) {
                  caca++;
                }
            }
            if (caca == 0) {
                pw.println(m.toString());
            }
            } 
        } catch (IOException ex) {
            Logger.getLogger(FormularioCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }   
     
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textocodigo = new javax.swing.JTextField();
        textonif = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textonombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoapellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoventas = new javax.swing.JTextField();
        botonactualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo");

        jLabel2.setText("NIF");

        textocodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textocodigoFocusLost(evt);
            }
        });
        textocodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textocodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        textonombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textonombreActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellidos");

        jLabel5.setText("Total Ventas");

        botonactualizar.setText("Actualizar");
        botonactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textonombre, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(textonif, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textocodigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoventas))
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoapellidos))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textonif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textonombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(textoapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textoventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonactualizar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textonombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textonombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textonombreActionPerformed

    private void botonactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonactualizarActionPerformed
        // TODO add your handling code here:
        Cliente a = new Cliente("111111", "12345678A", "Gomez", "Juan", 1250.00);
        this.listaClientes.add(a);
        Cliente b = new Cliente("111112", "87654321B", "Perez", "Laura", 0);
        this.listaClientes.add(b);
        Cliente c = new Cliente("111113", "14253674C", "Martin", "Pepe", 20.00);
        this.listaClientes.add(c);
        Cliente d = new Cliente("111114", "98752631A", "Comes", "Cristina", 0);
        this.listaClientes.add(d);
        leerFormulario();
        for (Cliente cliente : this.listaClientes) {
            for (Movimiento movimiento : this.listaMovimientos) {
                if(cliente.getCodigo().equals(movimiento.getCodigo())) {
                    cliente.setTotalventas(cliente.getTotalventas()+movimiento.getImporte());
                    JOptionPane.showConfirmDialog(this, "Total Ventas actualizado a: " + cliente.getTotalventas() + " a el CLIENTE con codigo: " + cliente.getCodigo(), "Actualizacion", JOptionPane.DEFAULT_OPTION);
                }
            }
        }
        comprobarClientes();
        comprobarFicheros();
    }//GEN-LAST:event_botonactualizarActionPerformed

    private void textocodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textocodigoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textocodigoFocusLost

    private void textocodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textocodigoActionPerformed
        if(!this.textocodigo.getText().matches("[0-9]+") || this.textocodigo.getText().length() > 6) {
            JOptionPane.showConfirmDialog(this, "Error", "Error", JOptionPane.OK_OPTION);
            this.textocodigo.grabFocus();
        }
        
    }//GEN-LAST:event_textocodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonactualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textoapellidos;
    private javax.swing.JTextField textocodigo;
    private javax.swing.JTextField textonif;
    private javax.swing.JTextField textonombre;
    private javax.swing.JTextField textoventas;
    // End of variables declaration//GEN-END:variables
}
