/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class EntradaDatos extends javax.swing.JFrame {
    /**
     * Creates new form EntradaDatos
     */
    public EntradaDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Textcodigo = new javax.swing.JTextPane();
        PanelNIF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextNIF = new javax.swing.JTextPane();
        PanelNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextNombre = new javax.swing.JTextPane();
        PanelApellidos = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextApellidos = new javax.swing.JTextPane();
        PanelDomicilio = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextDomicilio = new javax.swing.JTextPane();
        PanelCP = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextCP = new javax.swing.JTextPane();
        PanelLocalidad = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextLocalidad = new javax.swing.JTextPane();
        PanelTelefono = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        TextTelefono = new javax.swing.JTextPane();
        PanelMovil = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        TextMovil = new javax.swing.JTextPane();
        PanelFax = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        TextFax = new javax.swing.JTextPane();
        PanelMail = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        TextMail = new javax.swing.JTextPane();
        PanelTotal = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        TextTotal = new javax.swing.JTextPane();
        PanelLetra = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("0"); // NOI18N

        PanelCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelCodigoActionPerformed(evt);
            }
        });

        Textcodigo.setEditable(false);
        Textcodigo.setBorder(null);
        Textcodigo.setText("Código");
        Textcodigo.setOpaque(false);
        jScrollPane1.setViewportView(Textcodigo);

        PanelNIF.setName("0"); // NOI18N
        PanelNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelNIFActionPerformed(evt);
            }
        });

        TextNIF.setEditable(false);
        TextNIF.setBorder(null);
        TextNIF.setText("N.I.F.");
        TextNIF.setOpaque(false);
        jScrollPane2.setViewportView(TextNIF);

        PanelNombre.setName("0"); // NOI18N
        PanelNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelNombreActionPerformed(evt);
            }
        });

        TextNombre.setEditable(false);
        TextNombre.setBorder(null);
        TextNombre.setText("Nombre");
        TextNombre.setOpaque(false);
        jScrollPane3.setViewportView(TextNombre);

        PanelApellidos.setName("0"); // NOI18N
        PanelApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelApellidosActionPerformed(evt);
            }
        });

        TextApellidos.setEditable(false);
        TextApellidos.setBorder(null);
        TextApellidos.setText("Apellidos");
        TextApellidos.setOpaque(false);
        jScrollPane4.setViewportView(TextApellidos);

        PanelDomicilio.setName("0"); // NOI18N
        PanelDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelDomicilioActionPerformed(evt);
            }
        });

        TextDomicilio.setEditable(false);
        TextDomicilio.setBorder(null);
        TextDomicilio.setText("Domicilio");
        TextDomicilio.setOpaque(false);
        jScrollPane5.setViewportView(TextDomicilio);

        PanelCP.setFocusCycleRoot(true);
        PanelCP.setName("0"); // NOI18N
        PanelCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelCPActionPerformed(evt);
            }
        });

        TextCP.setEditable(false);
        TextCP.setBorder(null);
        TextCP.setText("C.P.");
        TextCP.setOpaque(false);
        jScrollPane6.setViewportView(TextCP);

        PanelLocalidad.setName("0"); // NOI18N
        PanelLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelLocalidadActionPerformed(evt);
            }
        });

        TextLocalidad.setEditable(false);
        TextLocalidad.setBorder(null);
        TextLocalidad.setText("Localidad");
        TextLocalidad.setOpaque(false);
        jScrollPane7.setViewportView(TextLocalidad);

        PanelTelefono.setName("0"); // NOI18N
        PanelTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelTelefonoActionPerformed(evt);
            }
        });

        TextTelefono.setEditable(false);
        TextTelefono.setBorder(null);
        TextTelefono.setText("Telefono");
        TextTelefono.setOpaque(false);
        jScrollPane8.setViewportView(TextTelefono);

        PanelMovil.setName("0"); // NOI18N
        PanelMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelMovilActionPerformed(evt);
            }
        });

        TextMovil.setEditable(false);
        TextMovil.setBorder(null);
        TextMovil.setText("Móvil");
        TextMovil.setOpaque(false);
        jScrollPane9.setViewportView(TextMovil);

        PanelFax.setName("0"); // NOI18N
        PanelFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelFaxActionPerformed(evt);
            }
        });

        TextFax.setEditable(false);
        TextFax.setBorder(null);
        TextFax.setText("Fax");
        TextFax.setOpaque(false);
        jScrollPane10.setViewportView(TextFax);

        PanelMail.setName("0"); // NOI18N
        PanelMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelMailActionPerformed(evt);
            }
        });

        TextMail.setEditable(false);
        TextMail.setBorder(null);
        TextMail.setText("e-mail");
        TextMail.setOpaque(false);
        jScrollPane11.setViewportView(TextMail);

        PanelTotal.setName("0"); // NOI18N
        PanelTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelTotalActionPerformed(evt);
            }
        });

        TextTotal.setEditable(false);
        TextTotal.setBorder(null);
        TextTotal.setText("Total");
        TextTotal.setOpaque(false);
        jScrollPane12.setViewportView(TextTotal);

        PanelLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanelLetraActionPerformed(evt);
            }
        });

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                                    .addComponent(PanelNombre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelCP, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(PanelTelefono))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(PanelLocalidad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 126, Short.MAX_VALUE))
                                            .addComponent(PanelMovil))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PanelTotal)
                                            .addComponent(PanelFax, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(PanelDomicilio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelMail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(64, 64, 64)
                .addComponent(Cancelar)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanelCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelNIFActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_PanelNIFActionPerformed

    private void PanelNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelNombreActionPerformed

    private void PanelApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelApellidosActionPerformed

    private void PanelDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelDomicilioActionPerformed

    private void PanelCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCPActionPerformed

    private void PanelLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelLocalidadActionPerformed

    private void PanelTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelTelefonoActionPerformed

    private void PanelMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMovilActionPerformed

    private void PanelFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelFaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelFaxActionPerformed

    private void PanelMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMailActionPerformed

    private void PanelTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelTotalActionPerformed

    private void PanelLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelLetraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelLetraActionPerformed

    private void PanelCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanelCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelCodigoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.PanelCodigo.setText("");
        this.PanelNIF.setText("");
        this.PanelLetra.setText("");
        this.PanelNombre.setText("");
        this.PanelApellidos.setText("");
        this.PanelDomicilio.setText("");
        this.PanelCP.setText("");
        this.PanelLocalidad.setText("");
        this.PanelTelefono.setText("");
        this.PanelMovil.setText("");
        this.PanelFax.setText("");
        this.PanelMail.setText("");
        this.PanelTotal.setText("");
    }//GEN-LAST:event_CancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if(this.PanelCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El codigo no puede estar vacio" ,"ErrorCodigo1", JOptionPane.OK_OPTION);
        }else if(!this.PanelCodigo.getText().matches("\\d{4}")){
            JOptionPane.showMessageDialog(this ,"El codigo tiene que tener 4 digitos" ,"ErrorCodigo2", JOptionPane.OK_OPTION);
        }else if(this.PanelNIF.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El NIF no puede estar vacio" ,"Error NIF1", JOptionPane.OK_OPTION);
        }else if(this.PanelNIF.getText().matches("\\d{8}")){
            JOptionPane.showMessageDialog(this ,"El NIF tiene que tener 8 digitos" ,"Error NIF2", JOptionPane.OK_OPTION);
        }else if(this.PanelLetra.getText().matches("\\[a-zA-Z]")){
            JOptionPane.showMessageDialog(this ,"El NIF tiene que que ser un caracter valido, entre a-z o A-Z" ,"ErrorLetra", JOptionPane.OK_OPTION);
        }else if(this.PanelNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El nombre no puede estar vacio" ,"ErrorNombre", JOptionPane.OK_OPTION);
        }else if(this.PanelApellidos.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El apellido no puede estar vacio" ,"ErrorApellidos", JOptionPane.OK_OPTION);
        }else if(this.PanelDomicilio.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El domicilio no puede estar vacio" ,"ErrorDomicilio", JOptionPane.OK_OPTION);
        }else if(this.PanelCP.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El CP no puede estar vacio" ,"ErrorCP", JOptionPane.OK_OPTION);
        }else if(this.PanelCP.getText().matches("\\d{5}")){
            JOptionPane.showMessageDialog(this ,"El CP tiene que ser de 5 digitos" ,"ErrorCP2", JOptionPane.OK_OPTION);
        }else if(this.PanelLocalidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El Localidad no puede estar vacio" ,"ErrorLocalidad", JOptionPane.OK_OPTION);
        }else if(this.PanelTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El telefono no puede estar vacio" ,"ErrorTelefono", JOptionPane.OK_OPTION);
        }else if(this.PanelTelefono.getText().matches("\\d{9}")){
            JOptionPane.showMessageDialog(this ,"El telefono tiene que ser de 9 digitos" ,"ErrorTelefono2", JOptionPane.OK_OPTION);
        }else if(this.PanelMovil.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El movil no puede estar vacio" ,"ErrorMovil", JOptionPane.OK_OPTION);
        }else if(this.PanelMovil.getText().matches("\\d{9}")){
            JOptionPane.showMessageDialog(this ,"El movil tiene que ser de 9 digitos" ,"ErrorMovil2", JOptionPane.OK_OPTION);
        }else if(this.PanelFax.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El fax no puede estar vacio" ,"ErrorFax", JOptionPane.OK_OPTION);
        }else if(this.PanelFax.getText().matches("\\d{9}")){
            JOptionPane.showMessageDialog(this ,"El fax tiene que ser de 9 digitos" ,"ErrorFax2", JOptionPane.OK_OPTION);
        }else if(this.PanelMail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El mail no puede estar vacio" ,"ErrorMail", JOptionPane.OK_OPTION);
        }else if(this.PanelMail.getText().matches("\\{a-zA-Z}@gmail.com")){
            JOptionPane.showMessageDialog(this ,"El mail no tiene el formato adecuado" ,"ErrorMail2", JOptionPane.OK_OPTION);
        }else if(this.PanelTotal.getText().isEmpty()){
            JOptionPane.showMessageDialog(this ,"El total no puede estar vacio" ,"ErrorTexto", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField PanelApellidos;
    private javax.swing.JTextField PanelCP;
    private javax.swing.JTextField PanelCodigo;
    private javax.swing.JTextField PanelDomicilio;
    private javax.swing.JTextField PanelFax;
    private javax.swing.JTextField PanelLetra;
    private javax.swing.JTextField PanelLocalidad;
    private javax.swing.JTextField PanelMail;
    private javax.swing.JTextField PanelMovil;
    private javax.swing.JTextField PanelNIF;
    private javax.swing.JTextField PanelNombre;
    private javax.swing.JTextField PanelTelefono;
    private javax.swing.JTextField PanelTotal;
    private javax.swing.JTextPane TextApellidos;
    private javax.swing.JTextPane TextCP;
    private javax.swing.JTextPane TextDomicilio;
    private javax.swing.JTextPane TextFax;
    private javax.swing.JTextPane TextLocalidad;
    private javax.swing.JTextPane TextMail;
    private javax.swing.JTextPane TextMovil;
    private javax.swing.JTextPane TextNIF;
    private javax.swing.JTextPane TextNombre;
    private javax.swing.JTextPane TextTelefono;
    private javax.swing.JTextPane TextTotal;
    private javax.swing.JTextPane Textcodigo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
